import { ART_DIR } from '../design.js';

/**
 * The bench shows an asset's label truncated to 22 characters, and older
 * exports carried that truncation through into the filename — so a design can
 * ask for "Realistic_Pine_Tree_PN" when the file on disk is
 * "Realistic_Pine_Tree_PNG_transparent.png". Rather than make the designer
 * retype names by hand into a data file, resolve what the design asked for
 * against what is actually in public/art.
 *
 * A browser cannot list a directory, so the listing is generated by the
 * art-index plugin in vite.config.js — served in dev, emitted at build.
 * If it is missing the name passes straight through and a real 404 speaks for
 * itself, which is the right failure: silently substituting art would be worse.
 */
let pending = null;

function index() {
  if (!pending) {
    pending = fetch(ART_DIR + 'index.json')
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => []);
  }
  return pending;
}

const warned = new Set();

export async function resolveArt(name) {
  const files = await index();
  if (!files.length || files.includes(name)) return name;
  // shortest first: the intended file is the one that adds least to the prefix
  const hits = files.filter((f) => f.startsWith(name)).sort((a, b) => a.length - b.length);
  if (!hits.length) return name;
  if (hits.length > 1 && !warned.has(name)) {
    warned.add(name);
    console.warn(`[art] "${name}" matches ${hits.length} files — using ${hits[0]}`);
  }
  return hits[0];
}
