/**
 * The About page's content plugin, and the editor's back end.
 *
 * Two jobs:
 *
 *   1. Substitution. about.html ships with __ABOUT_* placeholders; this fills
 *      them from about.content.json at serve time AND at build time, so the
 *      page you edit locally and the page that publishes are generated by the
 *      same code path. (The version plugin already works this way.)
 *
 *   2. A small dev-only API behind /__about/, which is what /about-editor.html
 *      talks to. It exists only in `configureServer`, so it is not present in a
 *      build and cannot be reached from the published site.
 */

import { existsSync, readdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, extname, basename } from 'node:path';
import { read, write, render, COLOURS } from './about.js';

const PUBLIC = resolve('public');
const IMAGE = /\.(png|jpe?g|webp|gif|svg)$/i;

/* A logo is written into public/ under its own name, so an upload can never
   land outside the folder however the file was named on the way in. */
function safeName(name) {
  const clean = basename(String(name || 'logo.png')).replace(/[^A-Za-z0-9._-]/g, '-');
  return IMAGE.test(clean) ? clean : clean + '.png';
}

function json(res, code, data) {
  res.statusCode = code;
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Cache-Control', 'no-store');
  res.end(JSON.stringify(data));
}

function readBody(req, limit = 12 * 1024 * 1024) {
  return new Promise((ok, no) => {
    const parts = [];
    let size = 0;
    req.on('data', (c) => {
      size += c.length;
      if (size > limit) { req.destroy(); no(new Error('too large')); return; }
      parts.push(c);
    });
    req.on('end', () => ok(Buffer.concat(parts)));
    req.on('error', no);
  });
}

export function aboutContent() {
  return {
    name: 'ridgeline-about-content',

    /* Only about.html carries the placeholders. The editor is plain HTML and
       must be left exactly as written, or its own markup would be rewritten. */
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!/about\.html$/.test(ctx.path || ctx.filename || '')) return html;
        if (!existsSync(resolve('about.content.json'))) return html;
        return render(html, read());
      }
    },

    configureServer(server) {
      /* The current content, plus what the editor needs to offer choices:
         which images are already in public/, and which colours exist. */
      server.middlewares.use('/__about/content', async (req, res, next) => {
        try {
          if (req.method === 'GET') {
            const images = existsSync(PUBLIC)
              ? readdirSync(PUBLIC).filter((f) => IMAGE.test(f)).sort()
              : [];
            return json(res, 200, { content: read(), images, colours: COLOURS });
          }
          if (req.method === 'POST') {
            const data = JSON.parse((await readBody(req)).toString('utf8'));
            if (!data || typeof data !== 'object' || Array.isArray(data)) {
              return json(res, 400, { error: 'expected an object' });
            }
            write(data);
            return json(res, 200, { ok: true });
          }
          next();
        } catch (e) {
          json(res, 500, { error: String(e && e.message || e) });
        }
      });

      /* A logo upload: raw bytes in the body, the intended name in a header,
         written into public/ where the page can reference it. */
      server.middlewares.use('/__about/logo', async (req, res, next) => {
        if (req.method !== 'POST') return next();
        try {
          const name = safeName(decodeURIComponent(req.headers['x-filename'] || ''));
          const buf = await readBody(req);
          if (!buf.length) return json(res, 400, { error: 'empty file' });
          writeFileSync(resolve(PUBLIC, name), buf);
          json(res, 200, { ok: true, name });
        } catch (e) {
          json(res, 500, { error: String(e && e.message || e) });
        }
      });

      /* Undo, for the one mistake this tool makes easy: overwriting good copy
         with bad. A snapshot is taken before every save the editor performs. */
      server.middlewares.use('/__about/snapshot', async (req, res, next) => {
        if (req.method !== 'POST') return next();
        try {
          const src = resolve('about.content.json');
          if (existsSync(src)) copyFileSync(src, resolve('about.content.bak.json'));
          json(res, 200, { ok: true });
        } catch (e) {
          json(res, 500, { error: String(e && e.message || e) });
        }
      });
    }
  };
}
